// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { BreakdownData, BreakdownErrors, BreakdownResponses, ConnectionsData, ConnectionsErrors, ConnectionsResponses, DocumentRoutesData, DocumentRoutesErrors, DocumentRoutesResponses, SummaryData, SummaryErrors, SummaryResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class UmbracoVercelAnalyticsService {
    public static connections<ThrowOnError extends boolean = false>(options?: Options<ConnectionsData, ThrowOnError>) {
        return (options?.client ?? client).get<ConnectionsResponses, ConnectionsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/vercel-analytics/connections',
            ...options
        });
    }
    
    public static documentRoutes<ThrowOnError extends boolean = false>(options: Options<DocumentRoutesData, ThrowOnError>) {
        return (options.client ?? client).get<DocumentRoutesResponses, DocumentRoutesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/vercel-analytics/documents/{documentId}/routes',
            ...options
        });
    }
    
    public static breakdown<ThrowOnError extends boolean = false>(options: Options<BreakdownData, ThrowOnError>) {
        return (options.client ?? client).get<BreakdownResponses, BreakdownErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/vercel-analytics/reports/breakdown/{dimension}',
            ...options
        });
    }
    
    public static summary<ThrowOnError extends boolean = false>(options?: Options<SummaryData, ThrowOnError>) {
        return (options?.client ?? client).get<SummaryResponses, SummaryErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/vercel-analytics/reports/summary',
            ...options
        });
    }
}
