// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5179' | (string & {});
};

export type AnalyticsBreakdown = {
    dimension: AnalyticsDimension;
    rows: Array<AnalyticsBreakdownRow>;
};

export type AnalyticsBreakdownRow = {
    value: string;
    pageViews: number;
    visitors: number;
};

export type AnalyticsConnectionSummary = {
    alias: string;
    displayName: string;
    isDefault: boolean;
    isConfigured: boolean;
    warnings: Array<string>;
};

export type AnalyticsConnectionsResponse = {
    enabled: boolean;
    defaultConnection?: string | null;
    defaultRangeDays: number;
    connections: Array<AnalyticsConnectionSummary>;
};

export type AnalyticsDimension = 'RequestPath' | 'Route' | 'ReferrerHostname' | 'Country' | 'DeviceType' | 'BrowserName' | 'OsName' | 'UtmSource' | 'UtmMedium' | 'UtmCampaign';

export type AnalyticsDocumentRoute = {
    connection: string;
    culture: string;
    hostname: string;
    path: string;
    url: string;
    isCurrent: boolean;
    warnings: Array<string>;
};

export type AnalyticsInterval = 'Day' | 'Week' | 'Month';

export type AnalyticsPoint = {
    timestamp: string;
    pageViews: number;
    visitors: number;
};

export type AnalyticsSummary = {
    totals: AnalyticsTotals;
    points: Array<AnalyticsPoint>;
};

export type AnalyticsTotals = {
    pageViews: number;
    visitors: number;
};

export type ConnectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracovercelanalytics/api/v1/connections';
};

export type ConnectionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ConnectionsResponses = {
    /**
     * OK
     */
    200: AnalyticsConnectionsResponse;
};

export type ConnectionsResponse = ConnectionsResponses[keyof ConnectionsResponses];

export type DocumentRoutesData = {
    body?: never;
    path: {
        documentId: string;
    };
    query?: {
        culture?: string;
    };
    url: '/umbraco/umbracovercelanalytics/api/v1/documents/{documentId}/routes';
};

export type DocumentRoutesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type DocumentRoutesResponses = {
    /**
     * OK
     */
    200: Array<AnalyticsDocumentRoute>;
};

export type DocumentRoutesResponse = DocumentRoutesResponses[keyof DocumentRoutesResponses];

export type BreakdownData = {
    body?: never;
    path: {
        dimension: AnalyticsDimension;
    };
    query?: {
        connection?: string;
        from?: string;
        to?: string;
        interval?: AnalyticsInterval;
        limit?: number;
        documentId?: string;
        culture?: string;
        path?: string;
    };
    url: '/umbraco/umbracovercelanalytics/api/v1/reports/breakdown/{dimension}';
};

export type BreakdownErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type BreakdownResponses = {
    /**
     * OK
     */
    200: AnalyticsBreakdown;
};

export type BreakdownResponse = BreakdownResponses[keyof BreakdownResponses];

export type SummaryData = {
    body?: never;
    path?: never;
    query?: {
        connection?: string;
        from?: string;
        to?: string;
        interval?: AnalyticsInterval;
        documentId?: string;
        culture?: string;
        path?: string;
    };
    url: '/umbraco/umbracovercelanalytics/api/v1/reports/summary';
};

export type SummaryErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SummaryResponses = {
    /**
     * OK
     */
    200: AnalyticsSummary;
};

export type SummaryResponse = SummaryResponses[keyof SummaryResponses];
